# Generated by Django 3.2.6 on 2022-06-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdrama', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kdrama',
            name='date_release',
            field=models.DateTimeField(),
        ),
    ]
