# Generated by Django 3.2.6 on 2022-06-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('movies_title', models.CharField(max_length=100)),
                ('id_genre', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
